#!/bin/bash

# shellcheck source=../lib-init-mock.bash
source ./lib-init-mock.bash

# External mock to allow error handling inside `if pacman ...`

exit_code=0

function pacman() {
	local command=
	local subcommand=
	local args=()
	local opt_quiet=false
	local opt_verbose=false
	local opt_explicit=false
	local opt_deps=false
	local opt_native=false
	local opt_foreign=false
	local opt_unrequired=0
	local opt_groups=0
	local opt_asdeps=false
	local opt_asexplicit=false

	local arg
	for arg in "$@"
	do
		case "$arg" in
			--query|--sync|--database|--remove)
				command=${arg#--}
				;;
			--list|--info|--owns)
				subcommand=${arg#--}
				;;
			--quiet)
				opt_quiet=true
				;;
			--verbose)
				opt_verbose=true
				;;
			--explicit)
				opt_explicit=true
				;;
			--deps)
				opt_deps=true
				;;
			--native)
				opt_native=true
				;;
			--foreign)
				opt_foreign=true
				;;
			--unrequired)
				opt_unrequired=$((opt_unrequired+1))
				;;
			--groups)
				opt_groups=$((opt_groups+1))
				;;
			--asdeps)
				opt_asdeps=true
				;;
			--asexplicit)
				opt_asexplicit=true
				;;
			-*)
				FatalError 'Unknown mocked pacman switch %s\n' "$(Color Y "$arg")"
				;;
			*)
				args+=("$arg")
		esac
	done

	if $opt_verbose
	then
		printf 'Cache Dirs: '
		printf '%s  ' '/var/cache/pacman/pkg'
		printf '\n'
	fi

	case "$command" in
		query)
			case "$subcommand" in
				'')
					$opt_quiet || FatalError 'Mocked pacman --query without --quiet\n'

					local found=false
					local name kind inst_as
					while IFS=$'\t' read -r name kind inst_as
					do
						if $opt_native && [[ "$kind" != native ]]
						then
							continue
						fi

						if $opt_foreign && [[ "$kind" != foreign ]]
						then
							continue
						fi

						if $opt_explicit && [[ "$inst_as" != explicit ]]
						then
							continue
						fi

						if $opt_deps && [[ "$inst_as" == explicit ]]
						then
							continue
						fi

						if [[ $opt_unrequired -eq 2 && "$inst_as" != orphan ]]
						then
							continue
						fi

						printf "%s\n" "$name"
						found=true
					done < "$test_data_dir"/packages.txt

					if ! $found
					then
						exit_code=1
					fi
					;;
				info)
					local package
					for package in "${args[@]}"
					do
						printf 'Name            : %s\n' "$package"
						printf 'Description     : %s\n' 'Dummy aconfmgr test suite package'
						printf 'Version         : %s\n' '1.0'
						printf 'Architecture    : %s\n' 'x86_64'
						printf '\n'
					done
					;;
				list)
					$opt_quiet || FatalError 'Mocked pacman --query --list without --quiet\n'

					local package
					find "$test_data_dir"/packages -mindepth 1 -maxdepth 1 -printf '%P\0' | \
						while read -r -d $'\0' package
						do
							find "$test_data_dir"/packages/"$package"/files \
								 -mindepth 1 \
								 -printf '%P\n' \
								| sed 's#^#/#'
						done \
							| sort -u
					;;
				owns)
					$opt_quiet || FatalError 'Mocked pacman --query --owns without --quiet\n'
					test "${#args[@]}" -eq 1 || FatalError 'Mocked pacman --query --owns expected 1 argument\n'

					local found=false

					local package _
					while IFS=$'\t' read -r package _
					do
						local fn="$test_data_dir"/packages/"$package"/files/"${args[0]}"
						if [[ -h "$fn" || -e "$fn" ]]
						then
							printf '%s\n' "$package"
							found=true
						fi
					done < "$test_data_dir"/packages.txt

					if ! $found
					then
						exit_code=1
					fi
					;;
				*)
					FatalError 'Unknown --query subcommand %s\n' "$subcommand"
					;;
			esac
			;;
		sync)
			if [[ $opt_groups -gt 0 ]]
			then
				[[ $opt_groups -eq 1 ]] || FatalError 'Mocked pacman --groups --groups not implemented\n'
				$opt_quiet || FatalError 'Mocked pacman --sync --groups without --quiet\n'
				[[ ${#args[@]} -eq 1 ]] || FatalError 'Mocked pacman --groups with more or less than 1 argument\n'
				local group=${args[0]}

				local package
				find "$test_data_dir"/packages -mindepth 1 -maxdepth 1 -printf '%P\0' | \
					while read -r -d $'\0' package
					do
						if [[ -f "$test_data_dir"/packages/"$package"/groups/"$group" ]]
						then
							printf '%s\n' "$package"
						fi
					done \
						| sort -u
			else
				echo pacman "$@" >> "$test_data_dir"/pacman.log
			fi
			;;
		database)
			local arg
			for arg in "${args[@]}"
			do
				if $opt_asdeps
				then
					sed -i 's/^\('"$(printf %q "$arg")"'\t.*\t\).*/\1orphan/' "$test_data_dir"/packages.txt
				elif $opt_asexplicit
				then
					sed -i 's/^\('"$(printf %q "$arg")"'\t.*\t\).*/\1explicit/' "$test_data_dir"/packages.txt
				else
					FatalError 'Mocked pacman --database without --asdeps/--asexplicit\n'
				fi
			done
			echo pacman "$@" >> "$test_data_dir"/pacman.log
			;;
		remove)
			local package
			for package in "${args[@]}"
			do
				sed -i "$(printf "/^%q\\t/d" "$package")" "$test_data_dir"/packages.txt

				local file
				find "$test_data_dir"/packages/"$package"/files \
					 -mindepth 1 \
					 -printf '%P\0' \
					| \
					while read -r -d '' file
					do
						local path="$test_data_dir"/files/"$file"
						if [[ ! -h "$path" && -d "$path" ]]
						then
							rmdir --ignore-fail-on-non-empty "$path"
						else
							rm -f "$path"
						fi

						rm -f "$test_data_dir"/file-props/"$file".{mode,owner,group}
					done
			done
			echo pacman "$@" >> "$test_data_dir"/pacman.log
			;;
		*)
			FatalError 'Unknown command %s\n' "$command"
			;;
	esac
}

pacman "$@"

Exit "$exit_code"
