#!/bin/bash

# shellcheck source=../lib-init-mock.bash
source ./lib-init-mock.bash

# External mock to allow execution via xargs

function stat() {
	local kind=
	local arg1=$1

	case "$arg1" in
		--format=%F)
			kind=type
			;;
		--format=%s)
			kind=size
			;;
		--format=%a)
			kind=mode
			;;
		--format=%U)
			kind=owner
			;;
		--format=%G)
			kind=group
			;;
		-f) # filesystem
			/usr/bin/stat "$@"
			return
			;;
		*)
			FatalError 'Unknown first argument to stat: %s\n' "$arg1"
			;;
	esac

	shift
	local arg
	for arg in "$@"
	do
		if [[ "$arg" == /* ]]
		then
			local path="$test_data_dir"/file-props/"$arg"."$kind"
			if [[ -f "$path" ]]
			then
				cat "$path"
				printf '\n'
			elif [[ "$kind" == owner || "$kind" == group ]]
			then
				printf 'root\n'
			else
				/usr/bin/stat "$arg1" "$test_data_dir"/files/"$arg"
			fi
		else
			/usr/bin/stat "$arg1" "$arg"
		fi
	done
}

stat "$@"

Exit 0
