#!/usr/bin/env bash

# shellcheck source=../lib-init-mock.bash
source ./lib-init-mock.bash

# External mock to allow execution via xargs

# Find the real stat binary using -p to bypass PATH and search system default paths
real_stat=$(command -v -p stat)

function stat() {
	local kind=
	local arg1=$1

	case "$arg1" in
		--format=%F)
			kind=type
			;;
		--format=%s)
			kind=size
			;;
		--format=%a)
			kind=mode
			;;
		--format=%U)
			kind=owner
			;;
		--format=%G)
			kind=group
			;;
		--format=%y)
			kind=mtime
			;;
		-f) # filesystem
			"$real_stat" "$@"
			return
			;;
		-*)
			FatalError 'Unknown first argument to stat: %s\n' "$arg1"
			;;
		*)
			# File existence check, output ignored
			kind=
			;;
	esac

	local args=("$real_stat")
	if [[ -n "$kind" ]]
	then
		args+=("$arg1")
		shift
	fi

	local arg
	for arg in "$@"
	do
		if [[ "$arg" == /* ]]
		then
			local path="$test_data_dir"/file-props/"$arg"."$kind"
			if [[ -f "$path" ]]
			then
				cat "$path"
				printf '\n'
			elif [[ "$kind" == owner || "$kind" == group ]]
			then
				printf 'root\n'
			else
				"${args[@]}" "$test_data_dir"/files/"$arg" || Exit 1
			fi
		else
			"${args[@]}" "$arg" || Exit 1
		fi
	done
}

stat "$@"

Exit 0
