#!/bin/bash
set -euo pipefail
source src/common.sh

AconfCompile

# Unknown packages (installed but not listed)

unknown_packages=($(comm -13 <(echo "${packages[*]}") <(echo "${installed_packages[*]}")))

if [[ ${#unknown_packages[@]} != 0 ]]
then
	printf "Removing %s unknown packages.\n" ${#unknown_packages[@]}
	sudo pacman --remove "${unknown_packages[@]}"
fi

# Missing packages (listed but not installed on current system)

missing_packages=($(comm -23 <(echo "${packages[*]}") <(echo "${installed_packages[*]}")))

if [[ ${#missing_packages[@]} != 0 ]]
then
	printf "Installing %s missing packages.\n" ${#missing_packages[@]}
	sudo pacman --sync --needed "${missing_packages[@]}"
fi

echo "Done."
