#!/bin/bash
# shellcheck disable=2030,2031
# SC2030/2031: https://github.com/koalaman/shellcheck/issues/732

set -eEuo pipefail
shopt -s lastpipe

IFS=$'\n'
export LC_COLLATE=C

if [[ -f ./aconfmgr && -f ./src/common.bash ]]
then
	# Running locally - use $PWD
	config_dir=./config
	tmp_dir=./tmp
	src_dir=src
else
	# Installed system-wide - use well-defined paths
	xdg_config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
	config_dir="$xdg_config_home"/aconfmgr
	tmp_dir="${TMPDIR:-/tmp}/aconfmgr-$USER"
	src_dir=/usr/lib/aconfmgr
fi

# shellcheck source=src/main.bash
source "$src_dir"/main.bash
