#!/bin/bash
# shellcheck disable=2031
# SC2031: https://github.com/koalaman/shellcheck/issues/732

aconfmgr_version=0.0.0

set -euo pipefail
shopt -s lastpipe

source src/common.bash
source src/save.bash
source src/apply.bash

function Usage() {
	printf "aconfmgr v%s\n" "${aconfmgr_version}"
	printf "Written by Vladimir Panteleev <aconfmgr@thecyber%s.net>\n" "shadow"
	printf "https://github.com/CyberShadow/aconfmgr\n"
	echo
	printf "Usage:  %s save|apply\n" "$0"
	echo
	printf "For more information, please refer to the full documentation at:\n"
	printf "https://github.com/CyberShadow/aconfmgr#readme\n"
}

function Main() {
	if [[ $# == 0 ]]
	then
		Usage
		Exit 2
	fi

	case "$1" in
		save)
			AconfSave
			;;
		apply)
			AconfApply
			;;
		*)
			Usage
			Exit 2
			;;
	esac

	Exit
}

Main "$@"
