.TH ACONFMGR 1
.SH NAME
aconfmgr \- a configuration manager for Arch Linux
.SH SYNOPSIS
.B aconfmgr
[\fIOPTIONS\fR]
.BR save " | " apply " | " check " | " diff
.SH DESCRIPTION
.B aconfmgr
is a package to track, manage, and restore the configuration of an Arch Linux system.

For a detailed description, please see the full documentation:

.I https://github.com/CyberShadow/aconfmgr#readme
.SH ACTIONS

.TP
.BR save
Update the configuration to reflect the current state of the system.

.TP
.BR apply
Update the system to reflect the current contents of the configuration.

.TP
.BR check
Syntax-check and lint the configuration.

.TP
.BR diff
Display a comparison between files in the configuration and the system.

This action takes a list of absolute paths, or additional options to pass
to \fBdiff\fR, as arguments following the action name.

.SH OPTIONS

.TP
.BR \-h ", " \-\-help
Output a usage message and exit.

.TP
.BR \-c ", " \-\-config " " \fIDIR\fR
Set the path to the configuration directory.

This directory will contain the configuration that
the \fBsave\fR command will write to, and
the \fBapply\fR command will read from, respectively.

See also \fBFILES\fR below.

.TP
.B \-\-skip-config
Skip the configuration parsing step, and reuse results from previous run.

.TP
.B \-\-skip-inspection
Skip the system inspection step, and reuse results from previous run.

.TP
.B \-\-skip-checksums
Skip the checksum verification of files belonging to installed packages.

When enabled, changes to a package's files are still detected through modification
time, size and other properties.

Enabling this option is generally safe and greatly speeds up execution speed,
but can fail to detect changes to a file's contents in exceptional circumstances,
such as filesystem corruption, intentional manipulation or badly behaved programs.

.TP
\fB\-\-aur-helper\fR \fIHELPER\fR
Set the AUR helper to use for installing foreign packages.

Supported values are
.BR aurman ", " pacaur ", " yaourt ", " yay ", " paru ", and " makepkg
(for which \fBaconfmgr\fR will download, resolve dependencies, and build/install itself).

.TP
\fB\-\-color\fR \fIWHEN\fR
When to use colors in output
.RB ( always / auto / never ).

If unset or set to \fBauto\fR, \fBaconfmgr\fR will use color when the output is determined to be a TTY.

If set, it is propagated appropriately to invoked programs.

.TP
\fB\-\-paranoid\fR
Always prompt before making any changes to the system.

The default is to not prompt when executed commands would themselves show a prompt before performing changes.

This option is mutually exclusive with \fB\-\-yes\fR.

If set, it is propagated appropriately to invoked programs.

.TP
\fB\-\-yes\fR
Never prompt before making any changes to the system.

This option is mutually exclusive with \fB\-\-paranoid\fR.

If set, it is propagated appropriately to invoked programs.

.TP
.BR \-v ", " \-\-verbose
 Show progress with additional detail.

.SH FILES
.TP
.I ~/.config/aconfmgr
Default location of configuration directory
(can be overridden with \fB\-c\fR).

The default location is affected by the \fB$XDG_CONFIG_HOME\fR and \fB$HOME\fR environment variables.

.TP
.IB /tmp/aconfmgr- USER
Temporary directory, used for intermediary system state and configuration output data, and other temporary files.

The location is affected by the \fB$TMPDIR\fR environment variable.

.SH "ENVIRONMENT VARIABLES"
.TP
.B $HOME
Affects the default location of the configuration directory.

.TP
.B $PACMAN
The command that will be used to check for missing dependencies and to install
and remove packages. \fBpacman\fR's
.IR -Qq ", " -Rns ", " -S ", " -T ", and " -U
operations must be supported by this command. If the variable is not set or empty, \fBaconfmgr\fR will fall back to 'pacman'.

.TP
.B $TMPDIR
Affects the default location of the temporary directory.

.TP
.B $XDG_CONFIG_HOME
Affects the default location of the configuration directory.

.SH BUGS
Please report defects and enhancement requests to the GitHub issue tracker:

.I https://github.com/CyberShadow/aconfmgr/issues

.SH AUTHORS

.de foo
.BR "bersh"
ad
..

\fBaconfmgr\fR is written by Vladimir Panteleev <aconfmgr@thecy\fRbersh\fRadow.net> and contributors:

.I https://github.com/CyberShadow/aconfmgr/graphs/contributors
