#!/bin/bash
# shellcheck disable=2031
# SC2031: https://github.com/koalaman/shellcheck/issues/732

aconfmgr_version=0.0.0

set -euo pipefail
shopt -s lastpipe

source src/common.bash
source src/save.bash
source src/apply.bash

function Usage() {
	printf "aconfmgr v%s\n" "${aconfmgr_version}"
	printf "Written by Vladimir Panteleev <aconfmgr@thecyber%s.net>\n" "shadow"
	printf "https://github.com/CyberShadow/aconfmgr\n"
	echo
	printf "Usage:  %s [OPTIONS]... save|apply\n" "$0"
	echo
	printf "Supported options:\n"
	printf "  -h, --help        Print this message\n"
	printf "  -c, --config DIR  Set the path to your configuration directory\n"
	echo
	printf "For more information, please refer to the full documentation at:\n"
	printf "https://github.com/CyberShadow/aconfmgr#readme\n"
}

function Main() {
	local command=

	while [[ $# != 0 ]]
	do
		case "$1" in
			save|apply)
				if [[ -z "$command" ]]
				then
					printf "A command has already been specified\n"
					false
				fi

				command="$1"
				shift
				;;
			-c|--config)
				config_dir="$2"
				shift 2
				;;
			-h|--help|help)
				Usage
				Exit 0
				;;
			*)
				Usage
				printf "\nUnrecognized option: %s\n" "$1"
				Exit 2
				;;
		esac
	done

	case "$command" in
		save)
			AconfSave
			;;
		apply)
			AconfApply
			;;
		*)
			Usage
			Exit 2
			;;
	esac

	Exit
}

Main "$@"
